### PR TITLE
Add symfony events for impersonate action

### PR DESCRIPTION
**Pull request by sharidas**
For the impersonate action and logout action
the symfony events are generated.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by PVince81** [comment]
@patrickjahns if core provides its own "OCGenericEvent" we could use that.
Otherwise we cannot have impersonate app specify its own custom "ImpersonateEvent" because then any app listening to it would need the impersonate app to be enabled to be able to use the "ImpersonateEvent" class.

**Comment by patrickjahns** [comment]
`OCGenericEvent` sounds better.

The last time I was thinking more about it, would be to have Events that are children of an event (maybe `OCGenericEvent` ) - and thus a auditor could subscribe to these events and that way filter out what he wants to know.

So the listening app would listen to AnyEvent that is based of the BaseClass. So no need to know the specific event upfront.

I guess now you are asking - how would the logger then know whats the content of the event etc? Last time I cam up with providing interfaces in core (`LoggableEvent`, `AuditableEvent`) that has a method which returns either a structured object that can be parsed, or an already pre-formatted string.

**Comment by PVince81** [comment]
@sharidas please raise a core ticket to discuss and implement a base class for GenericEvent and a list of occurrences we might need to replace

**Comment by PVince81** [comment]
raised https://github.com/owncloud/core/issues/32163 for using a custom event instead of GenericEvent

**Pull request merged**
