### PR TITLE
Strict checking for impersonation

### PR DESCRIPTION
**Pull request by sharidas**
Only allow users who are in the group
to be impersonated. Users of other group
which are not whitelisted cannot be
impersonated.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
Took little time to get the codecov happy. Now the coverage is improved.

**Comment by PVince81** [comment]
@DeepDiver1975 can you review ?

**Comment by DeepDiver1975** [comment]
Looks good. Not tested

**Comment by davitol** [comment]
> Looks good. Not tested

I have tested it and works 👍 jfyi

**Pull request merged**
